project_final/booking/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('booking_search', views.booking_search, name="booking_search"),
    path('booking_list', views.booking_list, name="booking_list"),
    path('table', views.table, name="table"),
    path('person', views.person, name="person"),
    path('date_special', views.date_special, name="date_special"),
    path('staff', views.staff, name="staff"),

    # API Routes
    path('table/<int:table_id>', views.table_update, name="table_update"),
    path('table_delete/<int:table_id>', views.table_delete, name="table_delete"),
    path('weekday_update', views.weekday_update, name="weekday_update"),
    path('date_detete/<int:date_id>', views.date_delete, name="date_delete"),
    path('staff_delete/<int:staff_id>', views.staff_delete, name="staff_delete"),
    path('booking_api', views.booking_api, name="booking_api"),
    path('booking_save_api', views.booking_save_api),
    path('get_booking', views.get_booking),
    path('booking_delete/<int:booking_id>', views.booking_delete),
    path('booking_honored/<int:booking_id>', views.booking_honored),
    path('booking_conflits', views.booking_conflits),
    path('client_api', views.client_api, name="client_api"),
    path('easy_client/<str:feature>', views.easy_client_api),
    path('client_update_api', views.client_update_api),
    path('client_delete_api/<int:client_id>', views.client_delete_api)
    
]

project_final/project_final/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls')),
]

project_final/booking/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.forms import ModelForm
from django import forms


CAPACITY_CHOICES = [
    (2, "2"),
    (4, "4"),
    (6, "6"),
    (8, "8"),
    (10, "10"),
    (12, "12"),
    (14, "14")
]
FORM_TYPE_CHOICES = [
    ("High", "High"),
    ("Standard", "Standard"),
    ("Low", "Low")
]

AREA_CHOICES = [
    ("UP", "Up Stair"),
    ("EXT", "Exterior"),
    ("MAI", "Main Room")
]


POSITION_CHOICES = [
    ("waiter", "waiter"),
    ("barman", "barman"),
    ("chef", "chef"),
    ("kitchen aid", "kitchen aid"),
    ("supervisor", "supervisor"),
    ("manager", "manager"),
    ("owner", "owner")
]

WEEKDAY_CHOICES = [
    ("mon", "Monday"),
    ("tue", "Tuesday"),
    ("wed", "Wednesday"),
    ("thu", "Thursday"),
    ("fri", "Friday"),
    ("sat", "Saturday"),
    ("sun", "Sunday"),
]

TIME_CHOICES = [
    ("lunch", "lunch"),
    ("dinner", "dinner")
]

## Models

class User(AbstractUser):
    pass

class Table(models.Model):
    is_active = models.BooleanField(default=True)
    is_joker = models.BooleanField(default=False)
    is_for_disabled = models.BooleanField(default=False)
    reference = models.CharField(max_length=6, unique=True, help_text="enter 6 characters max")
    area = models.CharField(
        max_length=3,
        choices=AREA_CHOICES,
        default="MAI"
    )
    capacity = models.IntegerField(
        choices=CAPACITY_CHOICES,
        default=2
    )
    form_type = models.CharField(
        max_length=10,
        choices=FORM_TYPE_CHOICES,
        verbose_name="Table height"
    )
    def __str__(self):
        return self.reference
# Creer des modèles distinct pour les choix si on veut que les managers puissent les définir.
# Et créer les pages qui le permettent.

class Client(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    tel = models.CharField(max_length=21, unique=True)
    is_foreign_phone = models.BooleanField(default=False)
    is_not_welcome = models.BooleanField(default=False)
    is_disabled = models.BooleanField(default=False)
    note = models.CharField(max_length=140, blank=True)

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def serialize(self):
        return {
            "first_name": self.first_name,
            "last_name": self.last_name,
            "tel": self.tel,
            "is_foreign_phone": self.is_foreign_phone,
            "is_not_welcome": self.is_not_welcome,
            "is_disabled": self.is_disabled,
            "note": self.note
        }

class WeekDayOpened(models.Model):
    weekday = models.CharField(
        max_length=3,
        choices=WEEKDAY_CHOICES,
        unique=True
    )
    at_lunch = models.BooleanField(default=False)
    at_dinner = models.BooleanField(default=False)

class DateSpecial(models.Model):
    date = models.DateField(unique=True)
    at_lunch = models.BooleanField(default=True)
    at_dinner = models.BooleanField(default=True)

class Staff(models.Model):
    is_active = models.BooleanField(default=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    short_name = models.CharField(max_length=5)
    position = models.CharField(
        max_length=15,
        choices=POSITION_CHOICES,
        blank=True
    )

class Booking(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name="booker")
    table = models.ForeignKey(Table, on_delete=models.CASCADE, null=True, related_name="booked_table")
    is_wanted_table = models.BooleanField(default=False)
    booking_date = models.DateField()
    booking_time = models.CharField(
        max_length=6,
        choices=TIME_CHOICES,
        default="lunch"
    )
    creation_date = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(Staff, on_delete=models.SET_NULL, null=True, blank=True)
    note = models.CharField(max_length=140, blank=True)
    honored = models.BooleanField(default=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['table', 'booking_date', 'booking_time'], name='unique_date_time_table')
        ]

## Forms

class TableForm(ModelForm):
    class Meta:
        model = Table
        fields = ['is_active', 'is_joker', 'is_for_disabled', 'area', 'reference', 'capacity', 'form_type']


class DateForm(ModelForm):
    class Meta:
        model = DateSpecial
        exclude = ['date']


class StaffForm(ModelForm):
    class Meta:
        model = Staff
        fields = '__all__'


class ClientForm(ModelForm):
    class Meta:
        model = Client
        exclude = ['note']

project_final/booking/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from django.shortcuts import HttpResponse, HttpResponseRedirect, render
from django.http import JsonResponse, HttpResponseForbidden, HttpResponseNotAllowed
from django.urls import reverse
from datetime import date, datetime, timedelta

import json
from django.core.serializers import serialize

from .models import User, Table, Client, WeekDayOpened, DateSpecial, Booking, Staff, TableForm, DateForm, StaffForm, ClientForm


# Create your views here.
def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("booking_list"))
        else:
            return render(request, "booking/login.html", {
                "message": "Invalid email and/or password."
            })
    else :
        return render(request, "booking/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def index(request):
    return render(request, "booking/index.html", {
        "today": datetime.today(),
        "booking_end": datetime.today() + timedelta(days=31)
    })

def booking_search(request):
    return render(request, "booking/booking_search.html", {
        "staffActive": Staff.objects.filter(is_active=True)
    })

def booking_list(request):
    today_obj = datetime.today().date()
    next_bookings = Booking.objects.filter(booking_date__gte=today_obj).order_by('booking_date', '-booking_time')
    # make a list of UNIQUE dates, to be able to iterate in the template and display the lunch / dinner button properly
    date_list = []
    current_date = ''
    for booking in next_bookings:
        temp = {
            'date': '',
            'lunch': False,
            'dinner': False
        }
        if booking.booking_date != current_date:
            temp['date'] = booking.booking_date
            current_date = booking.booking_date
            if booking.booking_time == 'lunch':
                temp['lunch'] = True
            if booking.booking_time == 'dinner':
                temp['dinner'] = True
            date_list.append(temp)
        else:
            if booking.booking_time == 'lunch':
                date_list[-1]['lunch'] = True
            if booking.booking_time == 'dinner':
                date_list[-1]['dinner'] = True

    return render(request, "booking/booking_list.html", {
        "date_list": date_list
    })

@login_required
def table(request):
    if request.method == "POST":
        table_form = TableForm(request.POST)
        if table_form.is_valid():
            table_form.save()
            return HttpResponseRedirect(reverse("table"))
        else:
            print("table_form is not valid!")
            return HttpResponse('transmited data are invalid', status=403)
    else:
        tables = Table.objects.all().order_by('area', 'reference')
        table_form = TableForm()

        return render(request, "booking/table.html", {
            "tables": tables,
            "table_form": table_form,
            # pass tables data as JSON format for javascript usage (when editing table for example)
            "tables_data": json.dumps(list(tables.values()))
        })


def person(request):
    return render(request, "booking/persons.html", {
        "client_form": ClientForm()
    })


@login_required
def date_special(request):
    if request.method == 'POST':
        start = datetime.strptime(request.POST['date'], '%Y-%m-%d')
        end = datetime.strptime(request.POST['date_end'], '%Y-%m-%d')
        # Basic checks
        if start < datetime.today():
            #REVENIR SUR LA GESTION DES ERREURS (RENVOYER PLUTOT VERS LA PAGE AVEC UN MESSAGE D ERROR)
            return HttpResponse("You can't add a date earlier than today", status=403)
        if start > end:
            return HttpResponse("You can't provide a end date earlier than start date", status=403)
        fields_list = request.POST.keys()

        # Deal with a period (start to end) if applicable
        if request.POST['period'] == "no":
            # if single date, set the end equal start to run the while loop only once
            end=start

        problem_happened=False
        delta = timedelta(days=1)
        while start <= end:
            # Create ou Update the start date
            date_temp, created = DateSpecial.objects.get_or_create(date=start)
            date_detailed = DateForm(request.POST, instance=date_temp)
            if date_detailed.is_valid():
                date_detailed.save()
            else:
                problem_happened=True
            start += delta
        if problem_happened:
            return HttpResponse("Something gone wrong", status=403)
        return HttpResponseRedirect(reverse("date_special"))

    else:
        return  render(request, "booking/date.html", {
            "weekdays": WeekDayOpened.objects.all(),
            "dates": DateSpecial.objects.filter(date__gte=datetime.today()),
            "date_form": DateForm(),
            "today": datetime.today()
        })


def staff(request):
    if request.method == "POST":
        if "staff_id" in request.POST:
            old_staff = Staff.objects.get(pk=request.POST['staff_id'])
            new_staff = StaffForm(request.POST, instance=old_staff)
        else:
            new_staff = StaffForm(request.POST)
        if new_staff.is_valid():
            new_staff.save()
            return HttpResponseRedirect(reverse('staff'))
        else:
            return HttpResponse('Something gone wrong with the submited staff', status=403)
    else:
        return render(request, "booking/staff.html", {
            "staffs": Staff.objects.all().order_by('position', 'last_name'),
            "staff_form": StaffForm()
        })



########################## API #################################
@login_required
def weekday_update(request):
    if request.method == 'POST':
        weekday_form_data = request.POST
        # starting with a weekdays variable with every time set to False
        # because the POST request only include checked box, unchecked ones are don't appear in the POST data
        weekdays = {
            'mon': {'lun': False, 'din': False},
            'tue': {'lun': False, 'din': False},
            'wed': {'lun': False, 'din': False},
            'thu': {'lun': False, 'din': False},
            'fri': {'lun': False, 'din': False},
            'sat': {'lun': False, 'din': False},
            'sun': {'lun': False, 'din': False}
        }
        # Update the weekdays variable with the data from the POST request
        for field in weekday_form_data:
            if len(field) == 7 and weekday_form_data[field] == 'on':
                day = field[:3]
                time = field[4:]
                weekdays[day][time] = True

        # iterate over the weekdays variable to update the database. Using the existing instance of each days.
        for day in weekdays:
            #day_instance = WeekDayOpened.objects.get_or_create(weekday=day)
            #Use the above line (instead of the line above) if the database is empty
            day_instance = WeekDayOpened.objects.get(weekday=day)
            day_instance.at_lunch = weekdays[day]['lun']
            day_instance.at_dinner = weekdays[day]['din']
            day_instance.save()

        return HttpResponseRedirect(reverse("date_special"))
    else:
        return HttpResponse("Wrong method.", status=400)

@login_required
def table_update(request, table_id):
    if request.method == "POST":
        table_old = Table.objects.get(pk=table_id)
        table_updated = TableForm(request.POST, instance=table_old)
        if table_updated.is_valid():
            table_updated.save()
            return HttpResponseRedirect(reverse("table"))
        else:
            print("transmited data are invalid")
            return HttpResponse('transmited data are invalid', status=403)
    else:
        return HttpResponse(status=405)

@login_required
def table_delete(request, table_id):
    table_to_delete = Table.objects.get(pk=table_id)
    delete_fct_return = table_to_delete.delete()
    if delete_fct_return[0] >= 1:
        return HttpResponseRedirect(reverse("table"))
    else:
        return HttpResponse("The table hasn't been deleted", status=403)

@login_required
def date_delete(request, date_id):
    date_to_delete = DateSpecial.objects.get(pk=date_id)
    delete_fct_return = date_to_delete.delete()
    if delete_fct_return[0] >= 1:
        return HttpResponse(status=200)
        #return HttpResponseRedirect(reverse("date_special"))
    else:
        return HttpResponse("The date hasn't been deleted", status=403)

@login_required
def staff_delete(request, staff_id):
    staff_to_delete = Staff.objects.get(pk=staff_id)
    delete_fct_return = staff_to_delete.delete()
    if delete_fct_return[0] >= 1:
        return HttpResponse(status=200)
    else:
        return HttpResponse("The date hasn't been deleted", status=403)


# Returns all the possibles bookings (from today to the next 31 days) regarding the criteria of search
@csrf_exempt
def booking_api(request):
    if request.method == 'POST':
        search_criteria = json.loads(request.body)

        # Creating a list of checked areas and a list of checked table height, to use it in query filters
        area_list = []
        if search_criteria['area-ext']:
            area_list.append("EXT")
        if search_criteria['area-mai']:
            area_list.append("MAI")
        if search_criteria['area-up']:
            area_list.append("UP")

project_final/booking/templates/booking/login.html
{% extends "booking/layout.html" %}

{% block body %}

    <div class="container-sm">
        <h2>Login</h2>

        {% if message %}
            <div>{{ message }}</div>
        {% endif %}

        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input autofocus class="form-control" type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <input class="btn btn-primary" type="submit" value="Login">
        </form>
    </div>

{% endblock %}

project_final/booking/templates/booking/page.html
<section id="table">
    <div class="container">
        <div id="existing-tables">
            <h2>Existing tables</h2>
            
            <table data-tables_data="{{ tables_data }}">
                {% regroup tables by get_area_display as area_list %}
                {% for area,tables_in_area in area_list %}
                    <tr><th colspan="2">{{ area }}</th><td></td><td></td></tr>
                    {% for table in tables_in_area %}
                        <tr>
                            <th></th>
                            <td><button type="button" class="btn btn-sm btn-warning edit-table" data-table_id="{{ table.id }}" data-bs-toggle="modal" data-bs-target="#edit_section">Edit</button></td>
                            <td class="center-cell">{{ table }}</td>
                            <td><button type="button" class="btn btn-sm btn-warning delete-table" data-table_id="{{ table.id }}">Delete</button></td>
                        </tr>
                    {% endfor %}
                {% endfor %}
            </table>

        <!-- Modal -->
        <div class="modal fade" id="edit_section" tabindex="-1" aria-labelledby="edit_section_label" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="edit_section_label">Edit Table</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'table' %}" method="PUT">
                        {% csrf_token %}
                        <table>
                            {{ table_form.as_table }}
                        </table>
                        <input  type="submit" value="Update table">
                    </form>
                </div>
            </div>
            </div>
        </div>

        <hr>

        </div>
        <div id="create-table">
            <h2>Create tables</h2>

            <form action="{% url 'table' %}" method="POST">
                {% csrf_token %}
                <table>
                    {{ table_form.as_table }}
                </table>
                <input type="submit" value="Create table">
            </form>
        </div>
    </div>
</section>

project_final/booking/templates/booking/staff.html
{% extends "booking/layout.html" %}
{% load static %}

{% block body %}

<section id="staff">
    <div class="container-sm">

        <div id="existing-staff">
            <div class="d-flex justify-content-between mb-2">
                <h2>Actual Staff</h2>
                <button type="button" class="btn btn-sm btn-primary add-staff" data-bs-toggle="modal" data-bs-target="#create_section">Add new employee</button>
            </div>
            <table data-staff_data="{{ staff_data }}" class="table table-light">
                {% regroup staffs by get_position_display as position_list %}
                {% for position,staffs_by_position in position_list %}
                    <tr><th class="text-start">{{ position }}</th><td colspan="3"></td></tr>
                    {% for staff in staffs_by_position %}
                        <tr data-staff_id="{{ staff.id }}" data-staff_is_active="{{ staff.is_active }}" data-staff_position="{{ staff.position }}"
                        {% if staff.is_active is not True %}
                        class="non-active"
                        {% endif %}>
                            <td><button type="button" class="btn btn-sm btn-warning edit-staff" data-bs-toggle="modal" data-bs-target="#edit_section">Edit</button></td>
                            <td class="staff_short_name">{{ staff.short_name }}</td>
                            <td><span class="staff_last_name">{{ staff.last_name }}</span> <span class="staff_first_name">{{ staff.first_name }}</span></td>
                            <td><button type="button" class="btn btn-sm btn-danger delete-staff" data-bs-toggle="modal" data-bs-target="#delete_confirmation">Delete</button></td>
                        </tr>
                    {% endfor %}
                {% endfor %}
            </table>
        </div>
        
        <!-- Modal For Create new Staff -->
        <div id="create_section" class="modal fade" tabindex="-1" aria-labelledby="create_section_label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="create_section_label">Create new staff member</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form action="{% url 'staff' %}" method="POST">
                            {% csrf_token %}
                            <table>
                                {{ staff_form.as_table }}
                            </table>
                            <input class='btn btn-primary' type="submit" value="Add">
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal For Editing Staff -->
        <div id="edit_section" class="modal fade" tabindex="-1" aria-labelledby="edit_section_label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="edit_section_label">Edit Person</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form action="/staff" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="staff_id" value="">
                            <table class="table">
                                {{ staff_form.as_table }}
                            </table>
                            <input class="btn btn-primary float-end" type="submit" value="Update staff">
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal For Deleting Staff member -->
        <div id="delete_confirmation" class="modal fade" tabindex="-1" aria-labelledby="delete_confirmation_label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="delete_confirmation_label">Delete Confirmation</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p id="delete_message">Are you sure, you want do delete this person?</p>
                        <button id="delete_confirm_btn" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Yes, delete it!</button>
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">No, keep it</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>

<script src="{% static 'booking/staff.js' %}"></script>

{% endblock %}

project_final/booking/templates/booking/table.html
{% extends "booking/layout.html" %}
{% load static %}

{% block body %}

<section id="table">
    <div class="container-sm">

        <div id="existing-tables">
            <div class="d-flex justify-content-between mb-2">
                <h2>Existing tables</h2>
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createModal">
                    Add Table
                </button>
            </div>
            <table data-tables_data="{{ tables_data }}" class="table table-light">
                {% regroup tables by get_area_display as area_list %}
                {% for area,tables_in_area in area_list %}
                    <tr><th colspan="2"><h4>{{ area }}</h4></th><td></td></tr>
                    {% for table in tables_in_area %}
                        <tr>
                            <td><button type="button" class="btn btn-sm btn-warning edit-table" data-table_id="{{ table.id }}" data-bs-toggle="modal" data-bs-target="#edit_section">Edit</button></td>
                            <td class="center-cell">{{ table }}</td>
                            <td><button type="button" class="btn btn-sm btn-danger delete-table" data-table_id="{{ table.id }}" data-table_ref="{{ table.reference }}" data-bs-toggle="modal" data-bs-target="#delete_confirmation">Delete</button></td>
                        </tr>
                    {% endfor %}
                {% endfor %}
            </table>
        </div>
        
        <!-- Modal For Creating Table -->
        <div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="createModalLabel">Create new table</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div id="create-table" class="modal-body">
                    <div id="create-reference-alert" class="alert alert-danger" role="alert">
                    </div>
                    <form action="{% url 'table' %}" method="POST">
                        {% csrf_token %}
                        <table class="table table-light">
                            {{ table_form.as_table }}
                        </table>
                        <input type="submit" class="btn btn-primary" value="Create table">
                    </form>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
            </div>
        </div>

        <!-- Modal For Editing Table -->
        <div id="edit_section" class="modal fade" tabindex="-1" aria-labelledby="edit_section_label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="edit_section_label">Edit Table</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div id="reference-alert" class="alert alert-danger" role="alert"></div>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <table class="table table-light">
                                {{ table_form.as_table }}
                            </table>
                            <input class="btn btn-primary" type="submit" value="Update table">
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal For Deleting Table -->
        <div id="delete_confirmation" class="modal fade" tabindex="-1" aria-labelledby="delete_confirmation_label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="delete_confirmation_label">Delete Confirmation</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p id="delete_message">Are you sure, you want do delete this table?</p>
                        <button id="delete_confirm_btn" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Yes, delete it!</button>
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">No, keep it</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>

<script src="{% static 'booking/table.js' %}"></script>

{% endblock %}